import { chmod, mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { cwd, execPath } from "node:process";

import type { GatewayConfig } from "../gateway/config.js";

export async function ensureAppOwnedCodexConfig(config: GatewayConfig): Promise<string> {
  await mkdir(config.codexHome, { recursive: true, mode: 0o700 });
  await mkdir(config.runtimeRoot, { recursive: true, mode: 0o700 });
  const managedHooksDirectory = join(config.codexHome, "managed-hooks");
  const hookAuditDirectory = join(config.codexHome, "hook-audit");
  const hookScriptPath = join(managedHooksDirectory, "commerce-runtime-hook.mjs");
  const hookAuditPath = join(hookAuditDirectory, "events.jsonl");
  const commerceWebMcpPath = resolve(cwd(), "dist/src/mcp/commerce-web-server.js");
  await mkdir(managedHooksDirectory, { recursive: true, mode: 0o700 });
  await mkdir(hookAuditDirectory, { recursive: true, mode: 0o700 });
  await writeFileIfChanged(hookScriptPath, renderManagedHookRunner(), 0o600);
  await writeFileIfChanged(join(config.runtimeRoot, "AGENTS.md"), renderRuntimeInstructions(), 0o600);
  const configPath = join(config.codexHome, "config.toml");
  const temporaryPath = join(config.codexHome, `.config.toml.${process.pid}.tmp`);
  const content = renderConfig(
    config,
    managedHooksDirectory,
    hookScriptPath,
    hookAuditPath,
    commerceWebMcpPath,
  );

  const existingConfig = await readTextFile(configPath);
  if (existingConfig !== content) {
    await writeFile(temporaryPath, content, { encoding: "utf8", mode: 0o600 });
    await rename(temporaryPath, configPath);
  } else {
    await chmod(configPath, 0o600);
  }
  return configPath;
}

async function writeFileIfChanged(path: string, content: string, mode: number): Promise<void> {
  if ((await readTextFile(path)) !== content) {
    await writeFile(path, content, { encoding: "utf8", mode });
  } else {
    await chmod(path, mode);
  }
}

async function readTextFile(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf8");
  } catch {
    return null;
  }
}

function renderConfig(
  config: GatewayConfig,
  managedHooksDirectory: string,
  hookScriptPath: string,
  hookAuditPath: string,
  commerceWebMcpPath: string,
): string {
  const hookCommand = [execPath, hookScriptPath, hookAuditPath].map(shellQuote).join(" ");
  const lines = [
    "# Generated by SHUEHO Commerce Pilot.",
    "# Provider secrets stay in environment variables and are never written here.",
    "# Local-development capabilities are disabled; only application-registered tools are allowed.",
    `model_provider = ${tomlString(config.provider.id)}`,
    'approval_policy = "never"',
    'sandbox_mode = "read-only"',
    "allow_login_shell = false",
    ...(process.env.NODE_ENV === "production" ? ["allow_managed_hooks_only = true"] : []),
    'file_opener = "none"',
    'web_search = "live"',
    "agents.enabled = true",
    "agents.max_concurrent_threads_per_session = 4",
    "analytics.enabled = false",
    "feedback.enabled = false",
  ];

  if (config.defaultModel) {
    lines.push(`model = ${tomlString(config.defaultModel)}`);
  }

  lines.push(
    "",
    "[features]",
    "image_generation = true",
    "shell_tool = false",
    "unified_exec = false",
    "shell_snapshot = false",
    "apps = false",
    "code_mode.enabled = false",
    "hooks = true",
    "memories = false",
    "multi_agent = true",
    "remote_plugin = false",
    "skill_mcp_dependency_install = false",
    "",
    "[apps._default]",
    "enabled = false",
    "default_tools_enabled = false",
    "destructive_enabled = false",
    "open_world_enabled = false",
    "",
    "[tools]",
    "# Keep the raw local-path image reader off until App Server has a tenant-only artifact mount.",
    "view_image = false",
    "web_search = true",
    "",
    "[shell_environment_policy]",
    'inherit = "none"',
    "ignore_default_excludes = false",
    "",
    "[mcp_servers.commerce_web]",
    `command = ${tomlString(execPath)}`,
    `args = [${tomlString(commerceWebMcpPath)}]`,
    `cwd = ${tomlString(cwd())}`,
    'env_vars = ["CODEX_HOME", "NODE_ENV", "COMMERCE_PROVIDER_API_KEY", "COMMERCE_PROVIDER_ID", "COMMERCE_PROVIDER_NAME", "COMMERCE_PROVIDER_BASE_URL", "COMMERCE_IMAGE_MODEL", "COMMERCE_AGENT_MODEL_SELECTORS", "COMMERCE_PROVIDER_MODEL_CACHE_TTL_MS", "COMMERCE_WEB_SEARCH_TIMEOUT_MS", "COMMERCE_WEB_SEARCH_MAX_ATTEMPTS", "CODEX_DEFAULT_MODEL", "CODEX_DEFAULT_MODEL_PROVIDER", "COMMERCE_GATEWAY_INTERNAL_TOKEN"]',
    "required = true",
    'enabled_tools = ["search"]',
    'default_tools_approval_mode = "auto"',
    "startup_timeout_sec = 15",
    `tool_timeout_sec = ${Math.ceil(
      ((config.provider.webSearchMaxAttempts > 1
        ? Math.min(config.provider.webSearchTimeoutMs, 45_000)
        : config.provider.webSearchTimeoutMs) +
        Math.max(0, config.provider.webSearchMaxAttempts - 1) * config.provider.webSearchTimeoutMs +
        15_000) /
        1_000,
    )}`,
    "",
    "[hooks]",
    `managed_dir = ${tomlString(managedHooksDirectory)}`,
    "",
  );

  for (const eventName of [
    "UserPromptSubmit",
    "PreToolUse",
    "PermissionRequest",
    "PostToolUse",
    "PreCompact",
    "PostCompact",
    "Stop",
    "SessionStart",
    "SessionEnd",
    "SubagentStart",
    "SubagentStop",
  ]) {
    lines.push(
      `[[hooks.${eventName}]]`,
      "",
      `[[hooks.${eventName}.hooks]]`,
      'type = "command"',
      `command = ${tomlString(hookCommand)}`,
      `timeout = ${eventName === "SessionEnd" ? 2 : 5}`,
      `statusMessage = ${tomlString(hookStatusMessage(eventName))}`,
      "",
    );
  }

  lines.push(
    `[model_providers.${config.provider.id}]`,
    `name = ${tomlString(config.provider.name)}`,
    `base_url = ${tomlString(config.provider.baseUrl)}`,
    `env_key = ${tomlString(config.provider.apiKeyEnvName)}`,
    'wire_api = "responses"',
    "requires_openai_auth = false",
    "request_max_retries = 4",
    "stream_max_retries = 5",
    "stream_idle_timeout_ms = 300000",
    "supports_websockets = false",
    "",
  );

  return `${lines.join("\n")}\n`;
}

function renderManagedHookRunner(): string {
  return `import { appendFile, mkdir } from "node:fs/promises";
import { dirname } from "node:path";

const auditPath = process.argv[2];
let raw = "";
for await (const chunk of process.stdin) {
  raw += chunk.toString("utf8");
  if (raw.length > 1_000_000) {
    process.stderr.write("Hook input exceeded the Commerce Pilot limit.\\n");
    process.exit(2);
  }
}

let input;
try {
  input = JSON.parse(raw || "{}");
} catch {
  process.stderr.write("Hook input was not valid JSON.\\n");
  process.exit(2);
}

const eventName = typeof input.hook_event_name === "string" ? input.hook_event_name : "unknown";
const toolName = typeof input.tool_name === "string" ? input.tool_name : null;
const allowedTools = new Set([
  "Agent",
  "spawn_agent",
  "send_input",
  "resume_agent",
  "wait_agent",
  "close_agent",
  "commerce_image.generate",
  "commerce_image_generate",
  "commerce_imagegenerate",
  "commerce_web.search",
  "commerce_web_search",
  "commerce_websearch",
  "web_search",
  "websearch",
  "mcp__commerce_web__search",
  "search",
  "generate",
]);

let output = {};
let decision = "observe";
if (eventName === "PreToolUse" && toolName && !allowedTools.has(toolName)) {
  decision = "deny";
  output = {
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "deny",
      permissionDecisionReason: "Tool is not registered in the Commerce Pilot runtime allowlist.",
    },
  };
} else if (eventName === "PermissionRequest") {
  decision = "deny";
  output = {
    hookSpecificOutput: {
      hookEventName: "PermissionRequest",
      decision: {
        behavior: "deny",
        message: "Commerce Pilot tools may not request host filesystem or process permissions.",
      },
    },
  };
}

if (auditPath) {
  await mkdir(dirname(auditPath), { recursive: true, mode: 0o700 });
  await appendFile(
    auditPath,
    JSON.stringify({
      at: new Date().toISOString(),
      eventName,
      sessionId: typeof input.session_id === "string" ? input.session_id : null,
      turnId: typeof input.turn_id === "string" ? input.turn_id : null,
      agentType: typeof input.agent_type === "string" ? input.agent_type : null,
      toolName,
      decision,
    }) + "\\n",
    { encoding: "utf8", mode: 0o600 },
  );
}

process.stdout.write(JSON.stringify(output));
`;
}

function hookStatusMessage(eventName: string): string {
  if (eventName === "PreToolUse" || eventName === "PermissionRequest") {
    return "正在检查 Commerce Pilot 工具策略";
  }
  if (eventName === "PostToolUse") {
    return "正在记录工具审计信息";
  }
  return "正在记录 Agent 生命周期";
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'"'"'`)}'`;
}

function renderRuntimeInstructions(): string {
  return [
    "# Commerce Pilot Runtime",
    "",
    "This runtime is an e-commerce agent product, not a local coding or system-administration agent.",
    "",
    "- Use application-registered Commerce Pilot tools plus explicitly enabled hosted web search and multi-agent collaboration.",
    "- Multi-agent workers inherit this same runtime policy and may not expand their permissions.",
    "- Local-path image reading is disabled; image understanding must use tenant-scoped application artifacts.",
    "- Never execute shell commands, inspect host files, modify local files, spawn processes, or request broader permissions.",
    "- Never claim that an external action succeeded without a successful registered-tool result.",
    "- Treat tool arguments and tool output as tenant-scoped commerce data.",
    "- Side-effecting commerce operations require the application-defined approval and readback flow.",
    "- If no registered tool can perform a requested action, explain that the capability is unavailable.",
    "",
  ].join("\n");
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}
