INSERT INTO quality_evaluation_case (id, query_text, document_text, expected_relevant, category)
VALUES
  (
    'taobao-spoon-material',
    '淘宝蘑菇勺价格带和消费者选择属性',
    '查询关键词：蘑菇勺；商品属性：材质；属性值：304不锈钢；搜索结果覆盖数量：141',
    true,
    'property'
  ),
  (
    'taobao-spoon-brand',
    '淘宝蘑菇勺品牌竞争、消费者选择属性和价格销量',
    '查询关键词：蘑菇勺；品牌候选：炊大皇；搜索结果覆盖数量：38',
    true,
    'brand'
  ),
  (
    'taobao-spoon-brand-phone',
    '淘宝蘑菇勺品牌竞争、消费者选择属性和价格销量',
    '查询关键词：蘑菇勺；品牌候选：华为手机壳；搜索结果覆盖数量：52',
    false,
    'cross_category_brand'
  ),
  (
    'taobao-spoon-silicone',
    '淘宝蘑菇勺品牌竞争、消费者选择属性和价格销量',
    '查询关键词：蘑菇勺；商品属性：材质；属性值：食品级硅胶；搜索结果覆盖数量：76',
    true,
    'property'
  ),
  (
    'taobao-spoon-stroller',
    '淘宝蘑菇勺品牌竞争、消费者选择属性和价格销量',
    '商品标题：婴儿轻便折叠推车；价格：399元；销量量级：500+',
    false,
    'cross_category'
  ),
  (
    'social-weixin-spoon-exact',
    '最近7天微信上蘑菇勺新品内容',
    '来源：微信；公众号：厨具观察；标题：蘑菇造型汤勺新品测评；发布时间：昨天',
    true,
    'social_exact'
  ),
  (
    'social-weixin-sports',
    '最近7天微信上蘑菇勺新品内容',
    '来源：微博；标题：NBA季后赛最新赛况；发布时间：今天',
    false,
    'social_cross_category'
  ),
  (
    'social-weixin-graphics-card',
    '最近7天微信上蘑菇勺新品内容',
    '来源：微信；公众号：数码前线；标题：RTX5090显卡首发评测；发布时间：今天',
    false,
    'social_cross_category'
  )
ON CONFLICT (id) DO UPDATE
SET query_text=EXCLUDED.query_text,
    document_text=EXCLUDED.document_text,
    expected_relevant=EXCLUDED.expected_relevant,
    category=EXCLUDED.category,
    active=true;
