"use client";

import { Check, ChevronRight, LoaderCircle, Plus, RefreshCw, Sparkles, X } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";

import { Button } from "@/components/ui/button";
import type { ProjectAiRevision } from "@/components/creative/project-ai-copilot";
import type { ConversationMessage } from "@/lib/agent/use-agent-thread";
import type { CreativeExpressionFormId, CreativeProject, CreativeTopic, CreativeTopicCategory, CreativeTopicOpportunity, CreativeTopicPlan } from "@/lib/creative/creative-space-adapter";
import { requirementBriefAdapter } from "@/lib/creative/requirement-brief-adapter";

type AiState = { status: "idle" | "connecting" | "running" | "completed" | "interrupted" | "failed"; error: string | null; messages: ConversationMessage[] };
type AiResult = { topics: CreativeTopic[]; weeklyAdvice: CreativeTopicPlan["weeklyAdvice"] };
type Filter = "全部" | "推荐" | CreativeTopicOpportunity;
const filters: Filter[] = ["全部", "推荐", "用户疑问", "使用痛点", "场景任务", "认知差", "实验验证", "购买决策"];
const exploreOptions = ["多找用户疑问", "多找真实痛点", "多找场景任务", "多找认知差", "多找可验证题目", "多找购买决策", "更适合小红书", "完全换一批"];

export function TopicPlanningWorkspace({ project, onSave, onRun, ai, onContinueToScript, revision }: { project: CreativeProject; onSave: (plan: CreativeTopicPlan) => void; onRun: (prompt: string) => Promise<boolean>; ai: AiState; onContinueToScript: () => void; revision?: ProjectAiRevision | null }) {
  const requirement = requirementBriefAdapter.get(project).brief;
  const [plan, setPlan] = useState(() => normalizePlan(project.topicPlan, project));
  const [step, setStep] = useState<1 | 2 | 3>(project.topicPlan?.topics.length ? 2 : 1);
  const [filter, setFilter] = useState<Filter>("全部");
  const [detail, setDetail] = useState<CreativeTopic | null>(null);
  const [pending, setPending] = useState<"pool" | "explore" | "manual" | null>(null);
  const [showExplore, setShowExplore] = useState(false);
  const [showManual, setShowManual] = useState(false);
  const [manual, setManual] = useState("");
  const applied = useRef<string | null>(null);
  const appliedRevision = useRef<string | null>(null);
  const parsed = useMemo(() => readResult(ai.messages), [ai.messages]);
  const running = ai.status === "connecting" || ai.status === "running";
  const update = (fn: (current: CreativeTopicPlan) => CreativeTopicPlan) => setPlan(fn);

  useEffect(() => { onSave(plan); }, [plan]);
  useEffect(() => {
    if (!pending || !parsed || applied.current === parsed.messageId) return;
    update((current) => ({ ...current, topics: pending === "manual" ? uniqueTopics([...current.topics, ...parsed.result.topics]) : parsed.result.topics, weeklyAdvice: parsed.result.weeklyAdvice }));
    if (pending === "manual" && parsed.result.topics[0]) setDetail(parsed.result.topics[0]);
    applied.current = parsed.messageId; setPending(null); setStep(2);
  }, [parsed, pending]);

  useEffect(() => {
    if (!revision || revision.chapter !== "选题" || revision.id === appliedRevision.current || !project.productBrief || !requirement || running) return;
    appliedRevision.current = revision.id;
    void onRun(buildPrompt("explore", project, requirement.analysis, plan, revision.instruction)).then((submitted) => {
      if (submitted) { setPending("explore"); setStep(2); }
    });
  }, [revision, project, requirement, plan, running, onRun]);

  if (!project.productBrief || !requirement) return <section className="mx-auto max-w-[1220px] border border-dashed border-[var(--cp-border)] bg-[var(--cp-bg-subtle)] p-8"><p className="m-0 text-sm font-semibold">选题需要已确认的上游上下文</p><p className="mb-0 mt-2 text-sm text-[var(--cp-text-muted)]">请先完成「产品确认」和「需求理解」，再基于产品事实与任务边界生成选题。</p></section>;
  const run = async (mode: "pool" | "explore" | "manual", extra = "") => { if (await onRun(buildPrompt(mode, project, requirement.analysis, plan, extra))) { setPending(mode); setShowExplore(false); setShowManual(false); if (mode === "manual") setManual(""); } };
  const selected = plan.topics.filter((item) => plan.selectedTopicIds.includes(item.id));
  const shown = plan.topics.filter((item) => filter === "全部" || filter === "推荐" ? filter === "全部" || item.priority === "高推荐" : item.opportunitySources?.includes(filter));
  const choose = (topic: CreativeTopic) => update((current) => ({ ...current, selectedTopicIds: current.selectedTopicIds.includes(topic.id) ? current.selectedTopicIds.filter((id) => id !== topic.id) : [...current.selectedTopicIds, topic.id] }));
  const chooseExpression = (topicId: string, formId: CreativeExpressionFormId) => update((current) => ({ ...current, expressionFormIds: { ...current.expressionFormIds, [topicId]: formId } }));
  const updateSettings = (patch: Partial<CreativeTopicPlan["settings"]>) => update((current) => ({ ...current, settings: { ...current.settings, ...patch }, topics: [], selectedTopicIds: [], expressionFormIds: {} }));

  return <section className="mx-auto max-w-[1220px] pb-20">
    <header className="border-b border-[var(--cp-border-subtle)] pb-7"><p className="m-0 text-xs font-semibold tracking-[0.1em] text-[#315c49]">内容决策 · 选题阶段</p><h3 className="mb-0 mt-3 text-[34px] font-semibold tracking-[-0.03em] text-[#315c49]">这轮最值得先拍什么</h3><p className="mb-0 mt-3 text-sm text-[var(--cp-text-muted)]">AI 基于用户问题、已验证产品事实和可执行证明方案，生成内容命题；选中后在本页匹配合适的表达形式。</p><div className="mt-6 flex flex-wrap gap-2">{["本轮目标", "选择选题", "匹配表达形式"].map((item, index) => <span key={item} className={["rounded-full px-3 py-1.5 text-xs", index < step ? "bg-[#315c49] text-white" : "bg-[var(--cp-bg-subtle)] text-[var(--cp-text-faint)]"].join(" ")}>{index + 1} · {item}</span>)}</div></header>
    <div className="mt-6 flex flex-wrap gap-x-8 gap-y-2 border-y border-[var(--cp-border-subtle)] py-4 text-xs text-[var(--cp-text-muted)]"><p className="m-0">产品：{project.products.map((item) => item.name).join("、") || "待关联"}</p><p className="m-0">目标：{plan.settings.objective}</p><p className="m-0">平台：{plan.settings.platforms.join(" / ")}</p></div>
    {step === 1 ? <GoalForm plan={plan} running={running} onSettings={updateSettings} onGenerate={() => void run("pool")} /> : step === 2 ? <section className="mt-8"><div className="mb-4 flex justify-end"><Button variant="outline" size="sm" onClick={() => setStep(1)}>返回设置目标</Button></div><div className="flex flex-wrap items-end justify-between gap-4"><div><h4 className="m-0 text-[28px] font-semibold tracking-[-0.02em]">选择选题</h4><p className="mb-0 mt-2 text-sm text-[var(--cp-text-muted)]">AI 已根据本轮任务、产品事实和用户问题，生成 {plan.topics.length} 个值得尝试的内容命题。</p></div><span className="text-xs text-[var(--cp-text-faint)]">点击卡片查看依据与证明方案</span></div><div className="mt-5 flex flex-wrap gap-2 border-y border-[var(--cp-border-subtle)] py-3">{filters.map((item) => <button key={item} type="button" onClick={() => setFilter(item)} className={["rounded-full px-3 py-1.5 text-xs", filter === item ? "bg-[#315c49] text-white" : "bg-[var(--cp-bg-subtle)] text-[var(--cp-text-muted)] hover:bg-[#eef3ed]"].join(" ")}>{item}</button>)}</div><TopicGroups topics={shown} selected={selected} onOpen={setDetail} onChoose={choose} />
      <div className="relative mt-8 flex flex-wrap gap-3 border-t border-[var(--cp-border-subtle)] pt-6"><Button variant="outline" disabled={running} onClick={() => setShowExplore((value) => !value)}>{running ? <LoaderCircle className="size-4 animate-spin" /> : <RefreshCw className="size-4" />}换一批</Button><Button variant="outline" onClick={() => setShowManual((value) => !value)}><Plus className="size-4" />自定义选题</Button>{showExplore ? <Popover title="想从哪个方向继续找？">{exploreOptions.map((option) => <button key={option} type="button" onClick={() => void run("explore", option)} className="rounded-full border border-[var(--cp-border)] px-3 py-2 text-xs hover:border-[#315c49] hover:bg-[#f1f7f1]">{option}</button>)}</Popover> : null}{showManual ? <Popover title="我想拍…"><input autoFocus value={manual} onChange={(event) => setManual(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && manual.trim()) void run("manual", manual); }} className="h-10 w-full rounded-[8px] border border-[var(--cp-border)] px-3 text-sm outline-none focus:ring-2 focus:ring-[var(--cp-focus)]" placeholder="例如：把喷嘴从底部移到下方，到底有什么用？" /><div className="mt-3 flex justify-end"><Button disabled={!manual.trim() || running} onClick={() => void run("manual", manual)}><Sparkles className="size-4" />整理并加入</Button></div></Popover> : null}</div>
      {selected.length ? <div className="sticky bottom-3 z-10 mt-6 flex flex-wrap items-center justify-between gap-4 rounded-[12px] border border-[#bcd0c0] bg-[#f3f8f1] px-4 py-3 shadow-sm"><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-semibold">已选 {selected.length} 条</span>{selected.slice(0, 3).map((topic) => <button key={topic.id} type="button" onClick={() => choose(topic)} className="max-w-52 truncate rounded-full bg-white px-2.5 py-1 text-xs text-[var(--cp-text-muted)]">{topic.topic} ×</button>)}</div><Button onClick={() => setStep(3)}>匹配表达形式<ChevronRight className="size-4" /></Button></div> : <p className="mb-0 mt-6 text-sm text-[var(--cp-text-muted)]">从卡片中选择至少一个选题后，再匹配表达形式。</p>}
    </section> : <ExpressionStep topics={selected} formIds={plan.expressionFormIds ?? {}} platforms={plan.settings.platforms} onBack={() => setStep(2)} onChoose={chooseExpression} onConfirm={() => { onSave({ ...plan, status: "已确认", version: plan.version + 1, confirmedAt: "刚刚" }); onContinueToScript(); }} />}
    {detail ? <TopicDrawer topic={detail} selected={plan.selectedTopicIds.includes(detail.id)} onClose={() => setDetail(null)} onChoose={() => choose(detail)} /> : null}
    {ai.error ? <p className="mt-5 text-sm text-[var(--cp-danger)]">选题生成未完成：{ai.error}</p> : null}
  </section>;
}

function GoalForm({ plan, running, onSettings, onGenerate }: { plan: CreativeTopicPlan; running: boolean; onSettings: (patch: Partial<CreativeTopicPlan["settings"]>) => void; onGenerate: () => void }) { const toggle = (value: string) => onSettings({ platforms: plan.settings.platforms.includes(value) ? plan.settings.platforms.filter((item) => item !== value) : [...plan.settings.platforms, value] }); return <section className="mt-8 grid gap-7 rounded-[14px] border border-[var(--cp-border)] bg-[#fffcf6] p-6 md:grid-cols-2"><Choice title="本次目标" items={["产品种草", "直播引流", "投流转化", "用户答疑", "内容测试", "品牌信任"]} value={plan.settings.objective} onPick={(objective) => onSettings({ objective })} single /><Choice title="目标平台" items={["抖音", "小红书", "视频号", "天猫投流"]} value={plan.settings.platforms} onPick={toggle} /><label className="text-sm font-semibold">期望候选数量<select value={plan.settings.quantity} onChange={(event) => onSettings({ quantity: Number(event.target.value) })} className="mt-3 h-11 w-full rounded-[8px] border border-[var(--cp-border)] bg-white px-3 text-sm font-normal"><option value={5}>5 条</option><option value={6}>6 条（推荐）</option><option value={8}>8 条</option></select></label><p className="self-end text-xs leading-5 text-[var(--cp-text-muted)]">资料不足时允许少于期望数量；不会为了凑数生成低证据或重复选题。</p><label className="text-sm font-semibold md:col-span-2">本轮资源与限制<textarea value={plan.settings.constraints} onChange={(event) => onSettings({ constraints: event.target.value })} className="mt-3 min-h-28 w-full rounded-[8px] border border-[var(--cp-border)] bg-white p-3 text-sm font-normal outline-none" placeholder="例如：只能拍厨房场景；暂不做竞品对比；需要手部演示。" /></label><div className="md:col-span-2 flex justify-end"><Button disabled={!plan.settings.platforms.length || running} onClick={onGenerate}>{running ? <LoaderCircle className="size-4 animate-spin" /> : <Sparkles className="size-4" />}生成选题池<ChevronRight className="size-4" /></Button></div></section>; }
const expressionForms: Array<{ id: CreativeExpressionFormId; description: string; goodFor: CreativeTopicOpportunity[] }> = [
  { id: "口播讲解", description: "用一个清晰观点解释结构、机制或选择理由。", goodFor: ["认知差", "购买决策"] },
  { id: "团队轻剧情", description: "用角色间的小冲突带出真实使用疑问。", goodFor: ["使用痛点", "用户疑问"] },
  { id: "产品演示", description: "用连续动作直接展示产品如何完成任务。", goodFor: ["场景任务", "用户疑问"] },
  { id: "情景演绎", description: "还原一个具体场景里的任务、麻烦与解决过程。", goodFor: ["场景任务", "使用痛点"] },
  { id: "实验对比", description: "以条件一致的观察、测试或对照证明结论。", goodFor: ["实验验证", "购买决策"] },
  { id: "Vlog记录", description: "跟随一次真实使用过程，自然呈现体验。", goodFor: ["场景任务", "使用痛点"] },
  { id: "混剪", description: "以多个短证据快速建立一个明确认知。", goodFor: ["认知差", "购买决策"] },
  { id: "直播切片", description: "截取主播现场答疑或演示中的一个高价值片段。", goodFor: ["用户疑问", "购买决策"] },
  { id: "图文快剪", description: "用短文字与关键画面快速讲清一个信息点。", goodFor: ["认知差", "用户疑问"] },
  { id: "美食菜谱", description: "在做菜任务中自然展示使用动作和结果。", goodFor: ["场景任务", "实验验证"] },
  { id: "问题答疑", description: "正面回应一个明确顾虑，再用事实和证明收束。", goodFor: ["用户疑问", "使用痛点", "购买决策"] },
];
function ExpressionStep({ topics, formIds, platforms, onBack, onChoose, onConfirm }: { topics: CreativeTopic[]; formIds: Record<string, CreativeExpressionFormId>; platforms: string[]; onBack: () => void; onChoose: (topicId: string, formId: CreativeExpressionFormId) => void; onConfirm: () => void }) { const complete = topics.every((topic) => Boolean(formIds[topic.id])); return <section className="mt-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><h4 className="m-0 text-[28px] font-semibold tracking-[-0.02em]">为选题匹配表达形式</h4><p className="mb-0 mt-2 text-sm text-[var(--cp-text-muted)]">根据选题的机会来源、产品依据和证明方案，优先推荐常用且可执行的形式；这一步不生成脚本。</p></div><Button variant="outline" size="sm" onClick={onBack}>返回选择选题</Button></div><div className="mt-7 space-y-5">{topics.map((topic) => { const forms = recommendedForms(topic, platforms); return <article key={topic.id} className="rounded-[14px] border border-[var(--cp-border)] bg-[#fffcf6] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="m-0 text-xs font-semibold text-[#315c49]">{topic.opportunitySources?.join(" · ") || opportunityFromCategory(topic.category)}</p><h5 className="mb-0 mt-2 text-lg font-semibold">{topic.topic}</h5><p className="mb-0 mt-2 text-sm text-[var(--cp-text-muted)]">重点证明：{topic.evidence?.proofPlan[0] || topic.proofPoints[0] || "待补充"}</p></div><span className="rounded-full bg-white px-3 py-1.5 text-xs text-[var(--cp-text-muted)]">{platforms.join(" / ")}</span></div><div className="mt-5 grid gap-3 lg:grid-cols-3">{forms.map((form, index) => <button key={form.id} type="button" onClick={() => onChoose(topic.id, form.id)} className={["rounded-[10px] border p-4 text-left transition", formIds[topic.id] === form.id ? "border-[#315c49] bg-[#edf4ed] ring-1 ring-[#315c49]" : "border-[var(--cp-border)] bg-white hover:border-[#8caf94]"].join(" ")}><div className="flex items-center justify-between gap-2"><span className="text-sm font-semibold">{form.id}</span>{index === 0 ? <span className="rounded-full bg-[#315c49] px-2 py-1 text-[10px] text-white">优先推荐</span> : null}</div><p className="mb-0 mt-2 text-xs leading-5 text-[var(--cp-text-muted)]">{form.description}</p><p className="mb-0 mt-3 text-[11px] text-[#315c49]">适合：{form.goodFor.join("、")}</p></button>)}</div></article>; })}</div><div className="sticky bottom-3 z-10 mt-7 flex flex-wrap items-center justify-between gap-4 rounded-[12px] border border-[#bcd0c0] bg-[#f3f8f1] px-4 py-3 shadow-sm"><p className="m-0 text-sm text-[var(--cp-text-muted)]">{complete ? `已为 ${topics.length} 条选题完成形式匹配` : `还需为 ${topics.length - Object.keys(formIds).filter((id) => topics.some((topic) => topic.id === id)).length} 条选题选择形式`}</p><Button disabled={!complete} onClick={onConfirm}>确认并进入脚本<ChevronRight className="size-4" /></Button></div></section>; }
function recommendedForms(topic: CreativeTopic, platforms: string[]) { const sources = topic.opportunitySources?.length ? topic.opportunitySources : [opportunityFromCategory(topic.category)]; const score = (form: typeof expressionForms[number]) => form.goodFor.reduce((total, source) => total + (sources.includes(source) ? 3 : 0), 0) + (platforms.includes("小红书") && form.id === "Vlog记录" ? 1 : 0) + (platforms.includes("抖音") && ["实验对比", "产品演示", "团队轻剧情"].includes(form.id) ? 1 : 0); return [...expressionForms].sort((left, right) => score(right) - score(left)).slice(0, 3); }
function TopicGroups({ topics, selected, onOpen, onChoose }: { topics: CreativeTopic[]; selected: CreativeTopic[]; onOpen: (topic: CreativeTopic) => void; onChoose: (topic: CreativeTopic) => void }) { const groups: Array<[string, CreativeTopic["priority"]]> = [["优先推荐", "高推荐"], ["值得尝试", "普通推荐"], ["探索选题", "探索型"]]; return <>{groups.map(([title, level]) => { const items = topics.filter((item) => item.priority === level); return items.length ? <div key={title} className="mt-8"><div className="mb-3 flex items-center gap-3"><h5 className="m-0 text-base font-semibold">{title}</h5><span className="h-px flex-1 bg-[var(--cp-border-subtle)]" /></div><div className="grid gap-3 md:grid-cols-2">{items.map((topic) => <TopicPreview key={topic.id} topic={topic} selected={selected.some((item) => item.id === topic.id)} onOpen={() => onOpen(topic)} onChoose={() => onChoose(topic)} />)}</div></div> : null; })}</>; }
function TopicPreview({ topic, selected, onOpen, onChoose }: { topic: CreativeTopic; selected: boolean; onOpen: () => void; onChoose: () => void }) { const evidence = topic.evidence?.productFacts[0] || topic.proofPoints[0] || "待补充产品依据"; return <article className={["relative min-h-[174px] rounded-[14px] border bg-white p-4", selected ? "border-[#315c49] ring-1 ring-[#315c49]" : "border-[var(--cp-border)] hover:border-[#a4bba9]"].join(" ")}><button type="button" aria-label={"查看选题：" + topic.topic} className="absolute inset-0 rounded-[14px]" onClick={onOpen} /><div className="pointer-events-none relative flex items-center justify-between gap-3"><span className={["text-xs font-semibold", topic.priority === "高推荐" ? "text-[#315c49]" : "text-[var(--cp-text-muted)]"].join(" ")}>{recommendationLabel(topic.priority)}</span><span className="max-w-[60%] truncate rounded-full bg-[var(--cp-bg-subtle)] px-2 py-1 text-[11px] text-[var(--cp-text-muted)]">{topic.opportunitySources?.join(" · ") || opportunityFromCategory(topic.category)}</span></div><h5 className="pointer-events-none relative mb-0 mt-3 text-base font-semibold leading-6">{topic.topic}</h5><p className="pointer-events-none relative mb-0 mt-2 line-clamp-2 text-sm leading-5 text-[var(--cp-text-muted)]">{topic.summary}</p><div className="pointer-events-none relative mt-3 truncate border-l-2 border-[#bcd0c0] pl-2 text-[11px] text-[var(--cp-text-muted)]">依据：{evidence}</div><div className="relative mt-3 flex justify-end"><button type="button" onClick={onChoose} className={["z-10 rounded-full px-2.5 py-1 text-xs", selected ? "bg-[#315c49] text-white" : "border border-[var(--cp-border)] bg-white text-[var(--cp-text-soft)]"].join(" ")}>{selected ? "已选择" : "选择"}</button></div></article>; }
function Popover({ title, children }: { title: string; children: React.ReactNode }) { return <div className="absolute left-0 top-[72px] z-20 w-[min(100%,560px)] rounded-[12px] border border-[var(--cp-border)] bg-white p-4 shadow-lg"><p className="m-0 text-sm font-semibold">{title}</p><div className="mt-3 flex flex-wrap gap-2">{children}</div></div>; }
function TopicDrawer({ topic, selected, onClose, onChoose }: { topic: CreativeTopic; selected: boolean; onClose: () => void; onChoose: () => void }) { const evidence = topic.evidence || { productFacts: topic.proofPoints, userSignals: [], proofPlan: topic.proofPoints }; return <><button type="button" aria-label="关闭选题详情" className="fixed inset-0 z-30 cursor-default bg-black/20" onClick={onClose} /><aside className="fixed inset-y-0 right-0 z-40 flex w-full max-w-[480px] flex-col border-l border-[var(--cp-border)] bg-[#fffdf9] shadow-2xl"><div className="flex items-start justify-between border-b border-[var(--cp-border-subtle)] p-6"><div><p className="m-0 text-xs font-semibold text-[#315c49]">{recommendationLabel(topic.priority)} · {topic.opportunitySources?.join(" · ") || opportunityFromCategory(topic.category)}</p><h4 className="mb-0 mt-2 text-2xl font-semibold leading-8">{topic.topic}</h4></div><button type="button" onClick={onClose} className="rounded-full p-2 text-[var(--cp-text-muted)] hover:bg-[var(--cp-bg-subtle)]"><X className="size-5" /></button></div><div className="flex-1 space-y-7 overflow-y-auto p-6"><p className="m-0 text-sm leading-6 text-[var(--cp-text-muted)]">{topic.summary}</p><Block title="为什么值得拍">{topic.reason}</Block><Block title="核心用户问题">{topic.keyQuestion}</Block><EvidenceBlock title="产品事实依据" items={evidence.productFacts} empty="未找到可确认的产品事实，不能作为优先选题。" /><EvidenceBlock title="用户依据" items={evidence.userSignals} empty="基于项目任务和需求理解推断，需后续用评论或客服问题验证。" /><EvidenceBlock title="建议证明方案" items={evidence.proofPlan} empty="尚未形成可执行的证明方案。" />{topic.valueAssessment ? <ScoreBlock value={topic.valueAssessment} /> : null}{topic.risks.length ? <Block title="待确认与表达提醒"><ul className="m-0 space-y-2 pl-4">{topic.risks.map((item) => <li key={item}>{item}</li>)}</ul></Block> : null}</div><div className="border-t border-[var(--cp-border-subtle)] p-5"><Button className="w-full" onClick={onChoose}>{selected ? <Check className="size-4" /> : <Plus className="size-4" />}{selected ? "已加入本轮选题" : "选择这个选题"}</Button></div></aside></>; }
function Block({ title, children }: { title: string; children: React.ReactNode }) { return <section><h5 className="m-0 text-sm font-semibold">{title}</h5><div className="mt-2 text-sm leading-6 text-[var(--cp-text-muted)]">{children}</div></section>; }
function EvidenceBlock({ title, items, empty }: { title: string; items: string[]; empty: string }) { return <Block title={title}>{items.length ? <ul className="m-0 space-y-2 pl-4">{items.map((item) => <li key={item}>{item}</li>)}</ul> : <p className="m-0 text-[var(--cp-text-faint)]">{empty}</p>}</Block>; }
function ScoreBlock({ value }: { value: NonNullable<CreativeTopic["valueAssessment"]> }) { const rows: Array<[string, number | undefined]> = [["用户相关度", value.userRelevance], ["产品关联度", value.productRelevance], ["信息价值", value.informationValue], ["证据强度", value.evidenceStrength], ["目标匹配度", value.objectiveFit]]; return <Block title="价值判断（仅作辅助判断）"><div className="grid grid-cols-2 gap-x-5 gap-y-2">{rows.map(([label, score]) => <p key={label} className="m-0 text-xs">{label}<span className="float-right font-semibold text-[var(--cp-text)]">{typeof score === "number" ? `${score}/5` : "待判断"}</span></p>)}</div></Block>; }
function Choice({ title, items, value, onPick, single = false }: { title: string; items: string[]; value: string | string[]; onPick: (item: string) => void; single?: boolean }) { return <div><p className="m-0 text-sm font-semibold">{title}</p><div className="mt-3 flex flex-wrap gap-2">{items.map((item) => { const active = single ? value === item : (value as string[]).includes(item); return <button key={item} type="button" onClick={() => onPick(item)} className={["rounded-full border px-3 py-2 text-sm", active ? "border-[#315c49] bg-[#315c49] text-white" : "border-[var(--cp-border)] bg-white"].join(" ")}>{item}</button>; })}</div></div>; }
function initialPlan(project: CreativeProject): CreativeTopicPlan { return { version: 0, status: "进行中", settings: { objective: "内容测试", platforms: project.platforms, quantity: 6, constraints: "" }, selectedTopicIds: [], topics: [], expressionFormIds: {}, weeklyAdvice: { priority: [], tests: [], deferred: [], needs: [] } }; }
function normalizePlan(value: CreativeTopicPlan | null, project: CreativeProject): CreativeTopicPlan { const initial = initialPlan(project); if (!value) return initial; const quantity = [5, 6, 8].includes(value.settings?.quantity) ? value.settings.quantity : initial.settings.quantity; const expressionFormIds = Object.fromEntries(Object.entries(value.expressionFormIds ?? {}).filter(([, formId]) => expressionForms.some((form) => form.id === formId))) as Record<string, CreativeExpressionFormId>; return { ...initial, ...value, settings: { ...initial.settings, ...value.settings, quantity }, selectedTopicIds: value.selectedTopicIds ?? [], topics: (value.topics ?? []).map((item) => normalizeTopic(item as unknown as Record<string, unknown>)).filter((item): item is CreativeTopic => Boolean(item)), expressionFormIds, weeklyAdvice: { ...initial.weeklyAdvice, ...value.weeklyAdvice } }; }
function normalizeTopic(value: Record<string, unknown>): CreativeTopic | null { const topic = str(value.topic) || str(value.title); if (!topic) return null; const sellingPoint = str(value.sellingPoint); const risk = str(value.risk); const legacyProof = strings(value.proofPoints).length ? strings(value.proofPoints) : sellingPoint ? [sellingPoint] : []; const productFacts = strings(value.productFacts).length ? strings(value.productFacts) : strings(record(value.evidence).productFacts).length ? strings(record(value.evidence).productFacts) : legacyProof; const userSignals = strings(value.userSignals).length ? strings(value.userSignals) : strings(record(value.evidence).userSignals); const proofPlan = strings(value.proofPlan).length ? strings(value.proofPlan) : strings(record(value.evidence).proofPlan).length ? strings(record(value.evidence).proofPlan) : legacyProof; return { id: str(value.id) || "topic-" + topic, topic, summary: str(value.summary) || [str(value.userEntry), sellingPoint].filter(Boolean).join("：") || "等待补充一句清晰的内容摘要。", category: category(str(value.category) || inferCategory(str(value.direction) || str(value.videoType))), priority: priority(str(value.priority) || str(value.level)), reason: str(value.reason) || "该选题与本轮产品信息和任务目标相关。", keyQuestion: str(value.keyQuestion) || str(value.userEntry) || "用户需要确认这件事是否真的有用。", proofPoints: proofPlan, risks: strings(value.risks).length ? strings(value.risks) : risk ? [risk] : [], source: value.source === "人工创建" ? "人工创建" : "AI生成", opportunitySources: opportunitySources(value, str(value.category) || str(value.direction) || str(value.videoType)), evidence: { productFacts, userSignals, proofPlan }, valueAssessment: assessment(value) }; }
function readResult(messages: ConversationMessage[]): { messageId: string; result: AiResult } | null { for (const message of [...messages].reverse()) { if (message.role !== "assistant" || message.status !== "completed") continue; try { const envelope = JSON.parse(message.content) as Record<string, unknown>; const value = typeof envelope.body === "string" ? JSON.parse(envelope.body) as Record<string, unknown> : envelope; const topics = Array.isArray(value.topics) ? value.topics.map((item) => item && typeof item === "object" ? normalizeTopic(item as Record<string, unknown>) : null).filter((item): item is CreativeTopic => Boolean(item)) : []; if (topics.length) return { messageId: message.id, result: { topics, weeklyAdvice: advice(value.weeklyAdvice) } }; } catch { /* Ignore non-JSON assistant messages. */ } } return null; }
function buildPrompt(mode: "pool" | "explore" | "manual", project: CreativeProject, requirement: NonNullable<ReturnType<typeof requirementBriefAdapter.get>["brief"]>["analysis"], plan: CreativeTopicPlan, extra: string) { const stage = mode === "pool" ? "选题池生成" : mode === "explore" ? "定向探索" : "整理自定义选题"; const target = mode === "manual" ? 1 : mode === "explore" ? 5 : plan.settings.quantity; return ["阶段：" + stage, "项目：" + project.name, "产品创作简报：" + JSON.stringify(project.productBrief), "需求理解：" + JSON.stringify(requirement), "本轮设置：" + JSON.stringify(plan.settings), mode === "explore" ? "探索偏好：" + extra : "", mode === "manual" ? "用户自定义想法：" + extra : "", `输出上限：${target} 条；资料或证据不足时允许更少，不得凑数。`, "你是短视频内容策划助手。先在内部按六类机会扫描：用户疑问、使用痛点、场景任务、认知差、实验验证、购买决策；它们是选题机会来源，可多选，不是互斥的视频类型。只输出可直接选择的具体内容命题，不输出抽象内容方向、标题党标题、表现形式或拍摄脚本。", "每条选题必须绑定：1) productFacts：来自产品创作简报的已验证产品事实或资料支持事实；2) userSignals：来自需求理解、任务或明确标记为推断的用户问题；3) proofPlan：可执行的实物、动作、对比或观察方案。已验证产品卖点可作为产品事实，但不能脱离用户问题和证明方案单独包装成选题。不要把计划中的实验当作已经验证的结果。", "优先推荐的硬门槛：至少 1 条产品事实 + 1 个明确用户问题/任务 + 1 个可执行证明方案，且符合本轮目标。缺少其中任一项只能标为探索型，并在 risks 写清待补资料。priority 仅可为 高推荐、普通推荐、探索型；评分只作为辅助，不得因数字看似精确而虚构用户数据。", "去重时忽略标题措辞，比较核心用户问题、核心产品事实、需要证明的结论；三项实质相同只能保留一条。", "每个 topic 必须包含：topic、summary、category、opportunitySources、priority、reason、keyQuestion、productFacts、userSignals、proofPlan、risks、valueAssessment（userRelevance、productRelevance、informationValue、evidenceStrength、objectiveFit，均为 1-5 的内部判断）。不得虚构事实、用户反馈、数据、认证、价格、功效或设计故事。请将唯一可解析的 JSON 对象放入回复的 body 字段；对象字段必须是 topics、weeklyAdvice。"].filter(Boolean).join("\n"); }
function uniqueTopics(topics: CreativeTopic[]) { return topics.filter((topic, index) => topics.findIndex((item) => item.topic === topic.topic) === index); }
function str(value: unknown) { return typeof value === "string" ? value : ""; }
function strings(value: unknown) { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : []; }
function record(value: unknown) { return value && typeof value === "object" ? value as Record<string, unknown> : {}; }
function opportunitySources(value: Record<string, unknown>, fallback: string): CreativeTopicOpportunity[] { const values = strings(value.opportunitySources).filter((item): item is CreativeTopicOpportunity => opportunityList.includes(item as CreativeTopicOpportunity)); return values.length ? values : [opportunityFromCategory(category(fallback))]; }
const opportunityList: CreativeTopicOpportunity[] = ["用户疑问", "使用痛点", "场景任务", "认知差", "实验验证", "购买决策"];
function opportunityFromCategory(value: CreativeTopicCategory): CreativeTopicOpportunity { if (value === "痛点") return "使用痛点"; if (value === "场景" || value === "使用体验") return "场景任务"; if (value === "实验") return "实验验证"; if (value === "对比") return "购买决策"; if (value === "反常识" || value === "原理" || value === "设计逻辑") return "认知差"; return "用户疑问"; }
function assessment(value: Record<string, unknown>): CreativeTopic["valueAssessment"] | undefined { const source = record(value.valueAssessment); const score = (key: string) => typeof source[key] === "number" && source[key] >= 1 && source[key] <= 5 ? source[key] : undefined; const result = { userRelevance: score("userRelevance"), productRelevance: score("productRelevance"), informationValue: score("informationValue"), evidenceStrength: score("evidenceStrength"), objectiveFit: score("objectiveFit") }; return Object.values(result).some((item) => item !== undefined) ? result : undefined; }
function recommendationLabel(value: CreativeTopic["priority"]) { return value === "高推荐" ? "优先推荐" : value === "普通推荐" ? "值得尝试" : "探索选题"; }
function category(value: string): CreativeTopicCategory { return (["原理", "功能", "使用体验", "痛点", "用户疑问", "实验", "对比", "场景", "反常识", "设计逻辑", "其他"] as const).includes(value as CreativeTopicCategory) ? value as CreativeTopicCategory : "其他"; }
function inferCategory(value: string): CreativeTopicCategory { if (/实验|测试/.test(value)) return "实验"; if (/对比|区别/.test(value)) return "对比"; if (/场景/.test(value)) return "场景"; if (/痛点|麻烦/.test(value)) return "痛点"; if (/原理|结构|设计/.test(value)) return "原理"; if (/使用|体验/.test(value)) return "使用体验"; return "其他"; }
function priority(value: string): CreativeTopic["priority"] { return value === "高推荐" || value === "优先拍摄" ? "高推荐" : value === "探索型" || value === "暂缓" ? "探索型" : "普通推荐"; }
function advice(value: unknown): CreativeTopicPlan["weeklyAdvice"] { const source = value && typeof value === "object" ? value as Record<string, unknown> : {}; return { priority: strings(source.priority), tests: strings(source.tests), deferred: strings(source.deferred), needs: strings(source.needs) }; }
