"use client";

import { Check, ChevronRight, LoaderCircle, Plus, RefreshCw, Sparkles, X } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";

import { Button } from "@/components/ui/button";
import type { ConversationMessage } from "@/lib/agent/use-agent-thread";
import type { CreativeProject, CreativeTopic, CreativeTopicCategory, CreativeTopicPlan } from "@/lib/creative/creative-space-adapter";
import { requirementBriefAdapter } from "@/lib/creative/requirement-brief-adapter";

type AiState = { status: "idle" | "connecting" | "running" | "completed" | "interrupted" | "failed"; error: string | null; messages: ConversationMessage[] };
type AiResult = { topics: CreativeTopic[]; weeklyAdvice: CreativeTopicPlan["weeklyAdvice"] };
type Filter = "全部" | "推荐" | CreativeTopicCategory;
const filters: Filter[] = ["全部", "推荐", "原理", "实验", "痛点", "对比", "场景", "使用体验"];
const exploreOptions = ["更有冲突", "更生活化", "更像小红书", "更像抖音", "更偏功能", "更偏实验", "更偏人物", "完全换一批"];

export function TopicPlanningWorkspace({ project, onSave, onRun, ai, onContinueToExpression }: { project: CreativeProject; onSave: (plan: CreativeTopicPlan) => void; onRun: (prompt: string) => Promise<boolean>; ai: AiState; onContinueToExpression: () => void }) {
  const requirement = requirementBriefAdapter.get(project).brief;
  const [plan, setPlan] = useState(() => normalizePlan(project.topicPlan, project));
  const [step, setStep] = useState<1 | 2>(project.topicPlan?.topics.length ? 2 : 1);
  const [filter, setFilter] = useState<Filter>("全部");
  const [detail, setDetail] = useState<CreativeTopic | null>(null);
  const [pending, setPending] = useState<"pool" | "explore" | "manual" | null>(null);
  const [showExplore, setShowExplore] = useState(false);
  const [showManual, setShowManual] = useState(false);
  const [manual, setManual] = useState("");
  const applied = useRef<string | null>(null);
  const parsed = useMemo(() => readResult(ai.messages), [ai.messages]);
  const running = ai.status === "connecting" || ai.status === "running";
  const update = (fn: (current: CreativeTopicPlan) => CreativeTopicPlan) => setPlan(fn);

  useEffect(() => { onSave(plan); }, [plan]);
  useEffect(() => {
    if (!pending || !parsed || applied.current === parsed.messageId) return;
    update((current) => ({ ...current, topics: pending === "manual" ? uniqueTopics([...current.topics, ...parsed.result.topics]) : parsed.result.topics, weeklyAdvice: parsed.result.weeklyAdvice }));
    if (pending === "manual" && parsed.result.topics[0]) setDetail(parsed.result.topics[0]);
    applied.current = parsed.messageId; setPending(null); setStep(2);
  }, [parsed, pending]);

  if (!project.productBrief || !requirement) return <section className="mx-auto max-w-[1220px] border border-dashed border-[var(--cp-border)] bg-[var(--cp-bg-subtle)] p-8"><p className="m-0 text-sm font-semibold">选题需要已确认的上游上下文</p><p className="mb-0 mt-2 text-sm text-[var(--cp-text-muted)]">请先完成「产品确认」和「需求理解」，再基于产品事实与任务边界生成选题。</p></section>;
  const run = async (mode: "pool" | "explore" | "manual", extra = "") => { if (await onRun(buildPrompt(mode, project, requirement.analysis, plan, extra))) { setPending(mode); setShowExplore(false); setShowManual(false); if (mode === "manual") setManual(""); } };
  const selected = plan.topics.filter((item) => plan.selectedTopicIds.includes(item.id));
  const shown = plan.topics.filter((item) => filter === "全部" || filter === "推荐" ? filter === "全部" || item.priority === "高推荐" : item.category === filter);
  const choose = (topic: CreativeTopic) => update((current) => ({ ...current, selectedTopicIds: current.selectedTopicIds.includes(topic.id) ? current.selectedTopicIds.filter((id) => id !== topic.id) : [...current.selectedTopicIds, topic.id] }));
  const updateSettings = (patch: Partial<CreativeTopicPlan["settings"]>) => update((current) => ({ ...current, settings: { ...current.settings, ...patch }, topics: [], selectedTopicIds: [] }));

  return <section className="mx-auto max-w-[1220px] pb-20">
    <header className="border-b border-[var(--cp-border-subtle)] pb-7"><p className="m-0 text-xs font-semibold tracking-[0.1em] text-[#315c49]">内容决策 · 选题阶段</p><h3 className="mb-0 mt-3 text-[34px] font-semibold tracking-[-0.03em] text-[#315c49]">这轮最值得先拍什么</h3><p className="mb-0 mt-3 text-sm text-[var(--cp-text-muted)]">AI 已读取产品创作简报与需求理解；先选具体题目，再决定用什么方式拍。</p><div className="mt-6 flex flex-wrap gap-2">{["本轮目标", "选择选题", "表现形式"].map((item, index) => <span key={item} className={["rounded-full px-3 py-1.5 text-xs", index < step ? "bg-[#315c49] text-white" : "bg-[var(--cp-bg-subtle)] text-[var(--cp-text-faint)]"].join(" ")}>{index + 1} · {item}</span>)}</div></header>
    <div className="mt-6 flex flex-wrap gap-x-8 gap-y-2 border-y border-[var(--cp-border-subtle)] py-4 text-xs text-[var(--cp-text-muted)]"><p className="m-0">产品：{project.products.map((item) => item.name).join("、") || "待关联"}</p><p className="m-0">目标：{plan.settings.objective}</p><p className="m-0">平台：{plan.settings.platforms.join(" / ")}</p></div>
    {step === 1 ? <GoalForm plan={plan} running={running} onSettings={updateSettings} onGenerate={() => void run("pool")} /> : <section className="mt-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><h4 className="m-0 text-[28px] font-semibold tracking-[-0.02em]">选择选题</h4><p className="mb-0 mt-2 text-sm text-[var(--cp-text-muted)]">每张卡是一条具体内容机会；点开后查看证据与风险，再加入本轮拍摄。</p></div><span className="text-xs text-[var(--cp-text-faint)]">已生成 {plan.topics.length} 条</span></div><div className="mt-5 flex flex-wrap gap-2 border-y border-[var(--cp-border-subtle)] py-3">{filters.map((item) => <button key={item} type="button" onClick={() => setFilter(item)} className={["rounded-full px-3 py-1.5 text-xs", filter === item ? "bg-[#315c49] text-white" : "bg-[var(--cp-bg-subtle)] text-[var(--cp-text-muted)] hover:bg-[#eef3ed]"].join(" ")}>{item}</button>)}</div><TopicGroups topics={shown} selected={selected} onOpen={setDetail} onChoose={choose} />
      <div className="relative mt-8 flex flex-wrap gap-3 border-t border-[var(--cp-border-subtle)] pt-6"><Button variant="outline" disabled={running} onClick={() => setShowExplore((value) => !value)}>{running ? <LoaderCircle className="size-4 animate-spin" /> : <RefreshCw className="size-4" />}换一批</Button><Button variant="outline" onClick={() => setShowManual((value) => !value)}><Plus className="size-4" />自定义选题</Button>{showExplore ? <Popover title="想从哪个方向继续找？">{exploreOptions.map((option) => <button key={option} type="button" onClick={() => void run("explore", option)} className="rounded-full border border-[var(--cp-border)] px-3 py-2 text-xs hover:border-[#315c49] hover:bg-[#f1f7f1]">{option}</button>)}</Popover> : null}{showManual ? <Popover title="我想拍…"><input autoFocus value={manual} onChange={(event) => setManual(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && manual.trim()) void run("manual", manual); }} className="h-10 w-full rounded-[8px] border border-[var(--cp-border)] px-3 text-sm outline-none focus:ring-2 focus:ring-[var(--cp-focus)]" placeholder="例如：把喷嘴从底部移到下方，到底有什么用？" /><div className="mt-3 flex justify-end"><Button disabled={!manual.trim() || running} onClick={() => void run("manual", manual)}><Sparkles className="size-4" />整理并加入</Button></div></Popover> : null}</div>
      {selected.length ? <div className="sticky bottom-3 z-10 mt-6 flex flex-wrap items-center justify-between gap-4 rounded-[12px] border border-[#bcd0c0] bg-[#f3f8f1] px-4 py-3 shadow-sm"><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-semibold">已选 {selected.length} 条</span>{selected.slice(0, 3).map((topic) => <button key={topic.id} type="button" onClick={() => choose(topic)} className="max-w-52 truncate rounded-full bg-white px-2.5 py-1 text-xs text-[var(--cp-text-muted)]">{topic.topic} ×</button>)}</div><Button onClick={() => { onSave({ ...plan, status: "已确认", version: plan.version + 1, confirmedAt: "刚刚" }); onContinueToExpression(); }}>下一步：表现形式<ChevronRight className="size-4" /></Button></div> : <p className="mb-0 mt-6 text-sm text-[var(--cp-text-muted)]">从卡片中选择至少一个选题后，再进入「表现形式」。</p>}
    </section>}
    {detail ? <TopicDrawer topic={detail} selected={plan.selectedTopicIds.includes(detail.id)} onClose={() => setDetail(null)} onChoose={() => choose(detail)} /> : null}
    {ai.error ? <p className="mt-5 text-sm text-[var(--cp-danger)]">选题生成未完成：{ai.error}</p> : null}
  </section>;
}

function GoalForm({ plan, running, onSettings, onGenerate }: { plan: CreativeTopicPlan; running: boolean; onSettings: (patch: Partial<CreativeTopicPlan["settings"]>) => void; onGenerate: () => void }) { const toggle = (value: string) => onSettings({ platforms: plan.settings.platforms.includes(value) ? plan.settings.platforms.filter((item) => item !== value) : [...plan.settings.platforms, value] }); return <section className="mt-8 grid gap-7 rounded-[14px] border border-[var(--cp-border)] bg-[#fffcf6] p-6 md:grid-cols-2"><Choice title="本次目标" items={["产品种草", "直播引流", "投流转化", "用户答疑", "内容测试", "品牌信任"]} value={plan.settings.objective} onPick={(objective) => onSettings({ objective })} single /><Choice title="目标平台" items={["抖音", "小红书", "视频号", "天猫投流"]} value={plan.settings.platforms} onPick={toggle} /><label className="text-sm font-semibold">目标选题数量<select value={plan.settings.quantity} onChange={(event) => onSettings({ quantity: Number(event.target.value) })} className="mt-3 h-11 w-full rounded-[8px] border border-[var(--cp-border)] bg-white px-3 text-sm font-normal"><option value={8}>8 条</option><option value={10}>10 条（推荐）</option><option value={13}>13 条</option></select></label><p className="self-end text-xs leading-5 text-[var(--cp-text-muted)]">首次生成给出少量可比较的候选，而不是一次堆出大量标题。</p><label className="text-sm font-semibold md:col-span-2">本轮资源与限制<textarea value={plan.settings.constraints} onChange={(event) => onSettings({ constraints: event.target.value })} className="mt-3 min-h-28 w-full rounded-[8px] border border-[var(--cp-border)] bg-white p-3 text-sm font-normal outline-none" placeholder="例如：只能拍厨房场景；暂不做竞品对比；需要手部演示。" /></label><div className="md:col-span-2 flex justify-end"><Button disabled={!plan.settings.platforms.length || running} onClick={onGenerate}>{running ? <LoaderCircle className="size-4 animate-spin" /> : <Sparkles className="size-4" />}生成选题池<ChevronRight className="size-4" /></Button></div></section>; }
function TopicGroups({ topics, selected, onOpen, onChoose }: { topics: CreativeTopic[]; selected: CreativeTopic[]; onOpen: (topic: CreativeTopic) => void; onChoose: (topic: CreativeTopic) => void }) { const groups: Array<[string, CreativeTopic["priority"]]> = [["优先测试", "高推荐"], ["值得尝试", "普通推荐"], ["延伸探索", "探索型"]]; return <>{groups.map(([title, level]) => { const items = topics.filter((item) => item.priority === level); return items.length ? <div key={title} className="mt-8"><div className="mb-3 flex items-center gap-3"><h5 className="m-0 text-base font-semibold">{title}</h5><span className="h-px flex-1 bg-[var(--cp-border-subtle)]" /></div><div className="grid gap-3 md:grid-cols-2">{items.map((topic) => <TopicPreview key={topic.id} topic={topic} selected={selected.some((item) => item.id === topic.id)} onOpen={() => onOpen(topic)} onChoose={() => onChoose(topic)} />)}</div></div> : null; })}</>; }
function TopicPreview({ topic, selected, onOpen, onChoose }: { topic: CreativeTopic; selected: boolean; onOpen: () => void; onChoose: () => void }) { return <article className={["relative min-h-[154px] rounded-[14px] border bg-white p-4", selected ? "border-[#315c49] ring-1 ring-[#315c49]" : "border-[var(--cp-border)] hover:border-[#a4bba9]"].join(" ")}><button type="button" aria-label={"查看选题：" + topic.topic} className="absolute inset-0 rounded-[14px]" onClick={onOpen} /><div className="pointer-events-none relative flex items-center justify-between gap-3"><span className={["text-xs font-semibold", topic.priority === "高推荐" ? "text-[#315c49]" : "text-[var(--cp-text-muted)]"].join(" ")}>{topic.priority === "高推荐" ? "★ 高推荐" : topic.priority}</span><span className="rounded-full bg-[var(--cp-bg-subtle)] px-2 py-1 text-[11px] text-[var(--cp-text-muted)]">{topic.category}</span></div><h5 className="pointer-events-none relative mb-0 mt-3 text-base font-semibold leading-6">{topic.topic}</h5><p className="pointer-events-none relative mb-0 mt-2 line-clamp-2 text-sm leading-5 text-[var(--cp-text-muted)]">{topic.summary}</p><div className="relative mt-3 flex items-center justify-between"><span className="rounded bg-[#f2f5f1] px-2 py-1 text-[11px] text-[#315c49]">{topic.source}</span><button type="button" onClick={onChoose} className={["z-10 rounded-full px-2.5 py-1 text-xs", selected ? "bg-[#315c49] text-white" : "border border-[var(--cp-border)] bg-white text-[var(--cp-text-soft)]"].join(" ")}>{selected ? "已选择" : "选择"}</button></div></article>; }
function Popover({ title, children }: { title: string; children: React.ReactNode }) { return <div className="absolute left-0 top-[72px] z-20 w-[min(100%,560px)] rounded-[12px] border border-[var(--cp-border)] bg-white p-4 shadow-lg"><p className="m-0 text-sm font-semibold">{title}</p><div className="mt-3 flex flex-wrap gap-2">{children}</div></div>; }
function TopicDrawer({ topic, selected, onClose, onChoose }: { topic: CreativeTopic; selected: boolean; onClose: () => void; onChoose: () => void }) { return <><button type="button" aria-label="关闭选题详情" className="fixed inset-0 z-30 cursor-default bg-black/20" onClick={onClose} /><aside className="fixed inset-y-0 right-0 z-40 flex w-full max-w-[480px] flex-col border-l border-[var(--cp-border)] bg-[#fffdf9] shadow-2xl"><div className="flex items-start justify-between border-b border-[var(--cp-border-subtle)] p-6"><div><p className="m-0 text-xs font-semibold text-[#315c49]">{topic.priority} · {topic.category}</p><h4 className="mb-0 mt-2 text-2xl font-semibold leading-8">{topic.topic}</h4></div><button type="button" onClick={onClose} className="rounded-full p-2 text-[var(--cp-text-muted)] hover:bg-[var(--cp-bg-subtle)]"><X className="size-5" /></button></div><div className="flex-1 space-y-7 overflow-y-auto p-6"><p className="m-0 text-sm leading-6 text-[var(--cp-text-muted)]">{topic.summary}</p><Block title="为什么值得拍">{topic.reason}</Block><Block title="核心问题">{topic.keyQuestion}</Block><Block title="需要拍到的证明点"><ul className="m-0 space-y-2 pl-4">{topic.proofPoints.map((item) => <li key={item}>{item}</li>)}</ul></Block>{topic.risks.length ? <Block title="表达提醒"><ul className="m-0 space-y-2 pl-4">{topic.risks.map((item) => <li key={item}>{item}</li>)}</ul></Block> : null}</div><div className="border-t border-[var(--cp-border-subtle)] p-5"><Button className="w-full" onClick={onChoose}>{selected ? <Check className="size-4" /> : <Plus className="size-4" />}{selected ? "已加入本轮选题" : "选择这个选题"}</Button></div></aside></>; }
function Block({ title, children }: { title: string; children: React.ReactNode }) { return <section><h5 className="m-0 text-sm font-semibold">{title}</h5><div className="mt-2 text-sm leading-6 text-[var(--cp-text-muted)]">{children}</div></section>; }
function Choice({ title, items, value, onPick, single = false }: { title: string; items: string[]; value: string | string[]; onPick: (item: string) => void; single?: boolean }) { return <div><p className="m-0 text-sm font-semibold">{title}</p><div className="mt-3 flex flex-wrap gap-2">{items.map((item) => { const active = single ? value === item : (value as string[]).includes(item); return <button key={item} type="button" onClick={() => onPick(item)} className={["rounded-full border px-3 py-2 text-sm", active ? "border-[#315c49] bg-[#315c49] text-white" : "border-[var(--cp-border)] bg-white"].join(" ")}>{item}</button>; })}</div></div>; }
function initialPlan(project: CreativeProject): CreativeTopicPlan { return { version: 0, status: "进行中", settings: { objective: "内容测试", platforms: project.platforms, quantity: 10, constraints: "" }, selectedTopicIds: [], topics: [], weeklyAdvice: { priority: [], tests: [], deferred: [], needs: [] } }; }
function normalizePlan(value: CreativeTopicPlan | null, project: CreativeProject): CreativeTopicPlan { const initial = initialPlan(project); if (!value) return initial; return { ...initial, ...value, settings: { ...initial.settings, ...value.settings }, selectedTopicIds: value.selectedTopicIds ?? [], topics: (value.topics ?? []).map((item) => normalizeTopic(item as unknown as Record<string, unknown>)).filter((item): item is CreativeTopic => Boolean(item)), weeklyAdvice: { ...initial.weeklyAdvice, ...value.weeklyAdvice } }; }
function normalizeTopic(value: Record<string, unknown>): CreativeTopic | null { const topic = str(value.topic) || str(value.title); if (!topic) return null; const sellingPoint = str(value.sellingPoint); const risk = str(value.risk); return { id: str(value.id) || "topic-" + topic, topic, summary: str(value.summary) || [str(value.userEntry), sellingPoint].filter(Boolean).join("：") || "等待补充一句清晰的内容摘要。", category: category(str(value.category) || inferCategory(str(value.direction) || str(value.videoType))), priority: priority(str(value.priority) || str(value.level)), reason: str(value.reason) || "该选题与本轮产品信息和任务目标相关。", keyQuestion: str(value.keyQuestion) || str(value.userEntry) || "用户需要确认这件事是否真的有用。", proofPoints: strings(value.proofPoints).length ? strings(value.proofPoints) : sellingPoint ? [sellingPoint] : [], risks: strings(value.risks).length ? strings(value.risks) : risk ? [risk] : [], source: value.source === "人工创建" ? "人工创建" : "AI生成" }; }
function readResult(messages: ConversationMessage[]): { messageId: string; result: AiResult } | null { for (const message of [...messages].reverse()) { if (message.role !== "assistant" || message.status !== "completed") continue; try { const value = JSON.parse(message.content) as Record<string, unknown>; const topics = Array.isArray(value.topics) ? value.topics.map((item) => item && typeof item === "object" ? normalizeTopic(item as Record<string, unknown>) : null).filter((item): item is CreativeTopic => Boolean(item)) : []; if (topics.length) return { messageId: message.id, result: { topics, weeklyAdvice: advice(value.weeklyAdvice) } }; } catch { /* Ignore non-JSON assistant messages. */ } } return null; }
function buildPrompt(mode: "pool" | "explore" | "manual", project: CreativeProject, requirement: NonNullable<ReturnType<typeof requirementBriefAdapter.get>["brief"]>["analysis"], plan: CreativeTopicPlan, extra: string) { const stage = mode === "pool" ? "选题池生成" : mode === "explore" ? "定向探索" : "整理自定义选题"; return ["阶段：" + stage, "项目：" + project.name, "产品创作简报：" + JSON.stringify(project.productBrief), "需求理解：" + JSON.stringify(requirement), "本轮设置：" + JSON.stringify(plan.settings), mode === "explore" ? "探索偏好：" + extra : "", mode === "manual" ? "用户自定义想法：" + extra : "", "先在内部评估结构、功能、使用方式、痛点、用户疑问、实验、对比、场景、反常识与设计逻辑等内容机会；不要输出“内容方向”或抽象方向卡。只输出可直接选择的具体选题池。首次生成控制在 10–13 条（约 3 条高推荐、5–7 条普通推荐、2–3 条探索型）；定向探索生成 5 条；自定义想法整理为 1 条并标记 source 为“人工创建”。topic 是内容主题，不是最终发布标题；summary 只用一句说明内容入口。每条必须提供真实可拍的 proofPoints，信息不足时写入 risks，不得虚构事实、评价、数据、认证、价格或功效。仅输出 JSON Schema 字段。"].filter(Boolean).join("\n"); }
function uniqueTopics(topics: CreativeTopic[]) { return topics.filter((topic, index) => topics.findIndex((item) => item.topic === topic.topic) === index); }
function str(value: unknown) { return typeof value === "string" ? value : ""; }
function strings(value: unknown) { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : []; }
function category(value: string): CreativeTopicCategory { return (["原理", "功能", "使用体验", "痛点", "用户疑问", "实验", "对比", "场景", "反常识", "设计逻辑", "其他"] as const).includes(value as CreativeTopicCategory) ? value as CreativeTopicCategory : "其他"; }
function inferCategory(value: string): CreativeTopicCategory { if (/实验|测试/.test(value)) return "实验"; if (/对比|区别/.test(value)) return "对比"; if (/场景/.test(value)) return "场景"; if (/痛点|麻烦/.test(value)) return "痛点"; if (/原理|结构|设计/.test(value)) return "原理"; if (/使用|体验/.test(value)) return "使用体验"; return "其他"; }
function priority(value: string): CreativeTopic["priority"] { return value === "高推荐" || value === "优先拍摄" ? "高推荐" : value === "探索型" || value === "暂缓" ? "探索型" : "普通推荐"; }
function advice(value: unknown): CreativeTopicPlan["weeklyAdvice"] { const source = value && typeof value === "object" ? value as Record<string, unknown> : {}; return { priority: strings(source.priority), tests: strings(source.tests), deferred: strings(source.deferred), needs: strings(source.needs) }; }
